### PR TITLE
implemented setup_aggregate and setup_vlan

### PR DESCRIPTION
**Pull request by skoef**
leoric mentioned the testing of sysding in #openindiana. I think it's worth a shot and would like to see these two functions to be included (as well as adding additional drives to the rpool, but I'll see to that later).

### CODE REVIEW

**Comment by pyhalov** [comment]
This change needs testing.

**Comment by skoef** [comment]
During testing, some issues came up and were fixed.

**Comment by pyhalov** [comment]
please, rebase commits to the latest head and merge them in one

**Comment by pyhalov** [comment]
It seems that something has gone terribly wrong during rebase/merge...

**Comment by xen0l** [comment]
Can this be merged as is?

**Comment by skoef** [comment]
Totally forgot all about this PR, will fix/rebase/whatever tomorrow!

**Review by olbohlen — CHANGES_REQUESTED** [review]
Hi,

line 258: if you use _link, please typedef it
line 234 and 240 : if ! echo foo | egrep bar works, but I would use if [ x${def_lcap} == xactive -o x${def_lcap} == xpassive -o x${def_lcap} == xoff ]; then... as it is easier to undestand (and keep in mind: protect the environment - save a fork() today! :))
at least comment on the egrep in 240 what this regex should match on

lines 289-306: the checks are good, but I wouldn't dladm create-vlan fail with a good error message if the parameters are wrong? that way we could keep the script shorter.

**Comment by skoef** [comment]
PR #3 replaces this PR.

**Pull request closed without merging**
