### PR TITLE
implemented setup_aggregate and setup_vlan

### PR DESCRIPTION
**Pull request by skoef**
In our usual setup, we use VLAN-tagged aggregate devices all the time, so I think this is something that should be part of sysding. It has been tested on some of our company's device.

Replacement of PR #1 since that one got all mangled up due to some rebasing mistake.

### CODE REVIEW

**Comment by olbohlen** [comment]
have you seen my comments in #1?

**Comment by skoef** [comment]
@olbohlen I did and you had some points. However, I'd rather keep the create-vlan check like it is, that way I make sure the error ends up in the log. Besides, it keeps error handling somewhat consistent throughout the script (see `setup_user_password` or `setup_ipmp` for similar error-handling)

**Comment by olbohlen** [comment]
yes, the code is from me ;) I'm fine with the additional checks.

**Comment by olbohlen** [comment]
oh and the typedef _link - shouldn't it be at the beginning of the function? everything else looks good, so +1 from me

**Review by xen0l — APPROVED** [review]

**Pull request merged**
